### PR TITLE
External chi2 update for RGE implementation.

### PR DESCRIPTION
**Pull request by arossia94**
PR for the update of the database files to make them compatible with the RGE implementation, including scale assignment.

- Updated interface_oos.py to make it compatible with the RGE implementation. I copied the solution proposed by Luca in the RGE PR.

### CODE REVIEW

**Comment by LucaMantani** [comment]
Hi @arossia94 , thanks for this! In the meantime we made a bit more efficient the external chi2 and restructured the files, so that patch I proposed in the PR needs to be adjusted.

**Comment by arossia94** [comment]
> Hi @arossia94 , thanks for this! In the meantime we made a bit more efficient the external chi2 and restructured the files, so that patch I proposed in the PR needs to be adjusted.

Thanks for letting me know, @LucaMantani. You can either let me know when the patch is adjusted or let me know where I should look at in order to understand the changes and adjust the patch myself.

**Comment by LucaMantani** [comment]
> > Hi @arossia94 , thanks for this! In the meantime we made a bit more efficient the external chi2 and restructured the files, so that patch I proposed in the PR needs to be adjusted.
> 
> Thanks for letting me know, @LucaMantani. You can either let me know when the patch is adjusted or let me know where I should look at in order to understand the changes and adjust the patch myself.

It should be fairly simple to adapt it, looking at how the chi2 is now defined in main. The idea is that there is an object calld incov that is precomputed once and for all:

```
incovs_reordered = []
        for path in self.datasets.values():
            invcov = np.loadtxt(current_file_path / path.format(collider=collider))
            temp = jnp.einsum("ij, jk, kl", self.project.T, invcov, self.project)
            incovs_reordered.append(temp)
        self.incov_tot = jnp.sum(jnp.array(incovs_reordered), axis=0)
```

with the rgemat, this will need to be multiplied in a similar manner, so that it's computed only once and then when the chi2 is called, we simply do something like
```
chi2_value = jnp.einsum("i, ij, j", coefficient_values, self.incov_tot, coefficient_values)
```

If it's not clear, I could have a go at it in the next days.

**Comment by LucaMantani** [comment]
@jacoterh I have implemented the RGE matrix in the external chi2 modules. If and when you are happy with it, we can merge.

**Comment by jacoterh** [comment]
Thanks both for all the amazing work! I'll have a look at this one too :)

**Review by jacoterh — APPROVED** [review]
Looks good to me!

**Pull request merged**
