### PR TITLE
Update ttbar numbers

### PR DESCRIPTION
**Pull request by LucaMantani**
This PR aims at updating the ttbar numbers to uniform them to the rest of the theory tables, using the same PDF sets and input parameters.

In doing so, bugs and precision of the numbers is also improved.

## Bugs:
- CMS_tt_13TeV_asy: first bin had the wrong binning, it was previously [0, 750], but it should have been >750

### CODE REVIEW

**Comment by LucaMantani** [comment]
Comparison new vs old theory predictions:

Linear individual fits:
  - [ATLAS_CMS_tt_AC_8TeV](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_ATLAS_CMS_tt_AC_8TeV.pdf)
  - [ATLAS_tt_13TeV_asy_2022](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_ATLAS_tt_13TeV_asy_2022.pdf)
  - [ATLAS_tt_13TeV_ljets_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_ATLAS_tt_13TeV_ljets_2016_Mtt.pdf)
  - [ATLAS_tt_8TeV_dilep_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_ATLAS_tt_8TeV_dilep_Mtt.pdf)
  - [ATLAS_tt_8TeV_ljets_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_ATLAS_tt_8TeV_ljets_Mtt.pdf)
  - [CMS_tt_13TeV_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_Mtt.pdf)
  - [CMS_tt_13TeV_asy](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_asy.pdf)
  - [CMS_tt_13TeV_dilep_2015_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_dilep_2015_Mtt.pdf)
  - [CMS_tt_13TeV_dilep_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_dilep_2016_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_2015_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_ljets_2015_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_ljets_2016_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_inc](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_13TeV_ljets_inc.pdf)
  - [CMS_tt_8TeV_ljets_Ytt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_CMS_tt_8TeV_ljets_Ytt.pdf)

Quadratic individual fits:
  - [ATLAS_CMS_tt_AC_8TeV](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_ATLAS_CMS_tt_AC_8TeV.pdf)
  - [ATLAS_tt_13TeV_asy_2022](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_ATLAS_tt_13TeV_asy_2022.pdf)
  - [ATLAS_tt_13TeV_ljets_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_ATLAS_tt_13TeV_ljets_2016_Mtt.pdf)
  - [ATLAS_tt_8TeV_dilep_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_ATLAS_tt_8TeV_dilep_Mtt.pdf)
  - [ATLAS_tt_8TeV_ljets_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_ATLAS_tt_8TeV_ljets_Mtt.pdf)
  - [CMS_tt_13TeV_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_Mtt.pdf)
  - [CMS_tt_13TeV_asy](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_asy.pdf)
  - [CMS_tt_13TeV_dilep_2015_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_dilep_2015_Mtt.pdf)
  - [CMS_tt_13TeV_dilep_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_dilep_2016_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_2015_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_ljets_2015_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_2016_Mtt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_ljets_2016_Mtt.pdf)
  - [CMS_tt_13TeV_ljets_inc](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_13TeV_ljets_inc.pdf)
  - [CMS_tt_8TeV_ljets_Ytt](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_CMS_tt_8TeV_ljets_Ytt.pdf)

Global fits:
  - [GLOBAL-LIN](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/LIN/report_GLOB_comp.pdf)
  - [GLOBAL-QUAD](https://github.com/LHCfitNikhef/smefit_database/blob/ttbar-theory-update/validation_reports/QUAD/report_GLOB_comp.pdf)

**Comment by jacoterh** [comment]
Hi @LucaMantani, thanks a lot for all the work! What I think would be helpful, also for reproducibility in the future, is to store the runcards that were used to produce these updated numbers in the [smefit_ewpo](https://github.com/LHCfitNikhef/smefit_ewpo/tree/main/madgraph/runcards) repo. We might have to rename it though as it will then also contain ttbar numbers as well. This would also be a good time to move all the yaml and json files to the smefit_release repo. What do you think?

**Comment by LucaMantani** [comment]
> Hi @LucaMantani, thanks a lot for all the work! What I think would be helpful, also for reproducibility in the future, is to store the runcards that were used to produce these updated numbers in the [smefit_ewpo](https://github.com/LHCfitNikhef/smefit_ewpo/tree/main/madgraph/runcards) repo. We might have to rename it though as it will then also contain ttbar numbers as well. This would also be a good time to move all the yaml and json files to the smefit_release repo. What do you think?

Yes, I think it's a good idea to store those info, in a dedicated repository. And I am also in favour of bringing data in the smefit_release repository

**Review by jacoterh — APPROVED** [review]
Looks good, superseded by [PR#74](https://github.com/LHCfitNikhef/smefit_predictions/pull/74#pullrequestreview-2448797859) on smefit_predictions.

**Comment by LucaMantani** [comment]
I removed the validation reports, ready to merge.

**Pull request merged**
