### PR TITLE
SMEFiT3.0 release: data + theory

### PR DESCRIPTION
**Pull request by jacoterh**
This PR contains the theory and data as used for the smefit3.0 paper

### CODE REVIEW

**Review by LucaMantani — APPROVED** [review]
What is the difference between commondata_projections and commondata_projections_L1? 

Anyways, great!

**Comment by jacoterh** [comment]
Ah I forgot to delete the commondata_projections one, let me fix that. There's supposed to be only L0 and L1.

**Comment by jacoterh** [comment]
Please merge if you're happy now :)

**Comment by jacoterh** [comment]
I also see I need to remove some unnecessary files from root, let me fix that as well

**Comment by LucaMantani** [comment]
Looks good, I'll merge :)

**Pull request merged**
