### PR TITLE
Split interface OOs by energy

### PR DESCRIPTION
**Pull request by arossia94**
Split the interface to external likelihoods for the OOs according to the centre of mass energy of the collider. Only the 365 GeV one includes the OOs for tt production. The classes for WW production are distinguished as OptimalWW{energy}.

They should be incorporated into a runcard as follows:

```
external_chi2:
   OptimalWW161: 
      path: /path_to_repo/smefit_database/external_chi2/optimal_observables/interface_oos_161.py
      scale: 161.0
   OptimalWW240: 
      path: /path_to_repo/smefit_database/external_chi2/optimal_observables/interface_oos_240.py
      scale: 240.0
   OptimalWW365: 
      path: /path_to_repo/smefit_database/external_chi2/optimal_observables/interface_oos_365.py
      scale: 365.0
   Optimaltt:
      path: /path_to_repo/smefit_database/external_chi2/optimal_observables/interface_oos.py
      scale: 365.0
```

Notice that the `interface_oos_{energy}.py` files are currently set up for FCCee only. This can be changed easily by modifying line 8 in each of them.

### CODE REVIEW

**Comment by LucaMantani** [comment]
Correct me if I'm wrong, in principle they do not need to stay in different files right? They can all be in the same, since they have different names?

**Comment by arossia94** [comment]
> Correct me if I'm wrong, in principle they do not need to stay in different files right? They can all be in the same, since they have different names?

You're right. I implemented this change now.

**Review by LucaMantani — APPROVED** [review]
Lovely, thanks for this!!

**Comment by LucaMantani** [comment]
We can merge to the dynamic scale branch directly

**Pull request merged**
