### PR TITLE
Add scales to theory files

### PR DESCRIPTION
**Pull request by LucaMantani**
This PR adds information on the energy scale for each theory file.

### CODE REVIEW

**Comment by LucaMantani** [comment]
@arossia94 @jacoterh The PR is ready for review. I think this is going to be tedious (as it was writing them 😂), but we should check them carefully (especially the ones that are dependent on the pT or other kinematic variables). Being inserted manually, the probability of a typo or a mistake somewhere is really high

**Comment by jacoterh** [comment]
Many thanks for this @LucaMantani! Looks like a lot of work indeed from your side! I will check

**Comment by arossia94** [comment]
All the LEP/FCCee/CEPC files and the inclusive datasets identified as such with the "_inc" suffix have been checked with the code `scale_checker.py` included in the theory folder. No need for corrections detected in those files.

All ATLAS differential (or not "_inc") datasets have been checked and corrected where needed. The files I corrected are:
-ATLAS_SSinc_RunII: one scale corrected in line 29.
-ATLAS_STXS_runII_13TeV(_uncorr)(_proj): gluon fusion scales corrected for pT binning.
-ATLAS_tt_AC_13TeV: corrected scale in line 13.
-ATLAS_ZH_Hbb_13TeV(_proj): corrected scales, the top mass had been used instead of the Higgs mass in the formula.

**Review by arossia94 — APPROVED** [review]

**Review by jacoterh — APPROVED** [review]
Should be ready to go guys!

**Comment by LucaMantani** [comment]
@jacoterh @arossia94 I removed 2 files called files_to_correct.dat and scale_checker.py, I don't think they should be in main ahah

**Pull request merged**
